#This is the remote application.yml

spring:
  mvc:
    servlet:
      path: /api

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  mail:
    username: fastfix2024project@gmail.com
    password: htybpaefxdufpruj
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

tankerkoenig:
  apiKey: 0bc4c8ca-21d0-ac93-2a74-4ae2a3afa795

key:
  access: A7tAmn11ToUsNooHAcycAHQlXs1cNeI931ZyG/WWPRc=
  refresh: fPw6Ln10Qjv2n9tSiwvc82x3UEMER/yetMihvE7NoK0=