spring:
  mvc:
    servlet:
      path: /api

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true

  datasource:
    url: jdbc:postgresql://localhost:5432/fast_fix
    username: admin
    driver-class-name: org.postgresql.Driver
    password: admin

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    username: fastfix2024project@gmail.com
    password: htybpaefxdufpruj
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

tankerkoenig:
  apiKey: 0bc4c8ca-21d0-ac93-2a74-4ae2a3afa795

key:
  access: A7tAmn11ToUsNooHAcycAHQlXs1cNeI931ZyG/WWPRc=
  refresh: fPw6Ln10Qjv2n9tSiwvc82x3UEMER/yetMihvE7NoK0=

logging:
  file:
    name: logs/log.log
  level:
    root: info