<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Account Deleted</title>
</head>
<body>
<h1 style="color: green">Email Address Change</h1>
<h2>Hello, ${name}!</h2>
<p>We regret that you have decided to delete your account.</p>
<p>We have processed all your data and deleted all the information we had about you.</p>
<h5>We will be very happy if you return to us in the future!</h5>
<p>Best regards, FastFix Team.</p>
</body>
</html>