<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Change Confirmation</title>
</head>
<body>
<h1 style="color: green">Password Change Confirmation</h1>
<h2>Hello, ${name}!</h2>
<p>Your password has been successfully changed.</p>
<p>If you did not make this change, please contact our support team immediately.</p>
<p>Best regards, FastFix Team.</p>
</body>
</html>