<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Technical Inspection Reminder</title>
</head>
<body>
<h1 style="color: green">Technical Inspection Reminder</h1>
<h2>Hello, ${name}!</h2>
<p>According to our records, the technical inspection for your car is due on ${date}.</p>
<p>Please schedule a technical inspection at your earliest convenience.</p>
<p>Best regards, FastFix Team.</p>
</body>
</html>
